name: BaileysThePug
favicon: null
layout_spectrum: 0.6091309920884669
typography_spectrum: 0.8352765566669405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9875220300164074
  lightness: 0.15498227369971573
  saturation: 0.010396886616945267
  rhythmicContrast: 0.9222626639530063
purpose: []
